# Generated by Django 4.1 on 2022-08-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_path', models.ImageField(default='', upload_to='shop_mart/images')),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Banners',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Cms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('meta_title', models.TextField()),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cms',
                'verbose_name_plural': 'Cms',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_key', models.CharField(max_length=45)),
                ('conf_value', models.CharField(max_length=100)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('modify_status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('contact_no', models.CharField(max_length=45)),
                ('message', models.TextField()),
                ('note_admin', models.TextField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ContactUs',
                'verbose_name_plural': 'ContactUs',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45)),
                ('percent_off', models.FloatField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('no_of_user', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupon',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EmailTemplate',
                'verbose_name_plural': 'EmailTemplate',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PaymentGateway',
                'verbose_name_plural': 'PaymentGateway',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=45)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.TextField()),
                ('price', models.FloatField()),
                ('special_price_from', models.DateTimeField()),
                ('special_price_to', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('meta_title', models.TextField()),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ProductAttributes',
                'verbose_name_plural': 'ProductAttributes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('to_token', models.CharField(max_length=100)),
                ('twitter_token', models.CharField(max_length=100)),
                ('google_token', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('M', 'MANAGER'), ('C', 'CUSTOMER')], default='', max_length=10)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.user')),
            ],
            options={
                'verbose_name': 'UserWishList',
                'verbose_name_plural': 'UserWishList',
            },
        ),
        migrations.CreateModel(
            name='userOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.IntegerField()),
                ('AWB_NO', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('grand_total', models.FloatField()),
                ('shipping_charges', models.FloatField()),
                ('billing_address_1', models.CharField(max_length=100)),
                ('billing_address_2', models.CharField(max_length=100)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=100)),
                ('billing_country', models.CharField(max_length=100)),
                ('billing_zipcode', models.CharField(max_length=100)),
                ('shipping_address_1', models.CharField(max_length=100)),
                ('shipping_address_2', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_country', models.CharField(max_length=100)),
                ('shipping_zipcode', models.CharField(max_length=100)),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.coupon')),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.paymentgateway')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.user')),
            ],
            options={
                'verbose_name': 'userOrder',
                'verbose_name_plural': 'userOrder',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('zip_code', models.CharField(max_length=45)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.user')),
            ],
            options={
                'verbose_name': 'UserAddress',
                'verbose_name_plural': 'UserAddress',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.product')),
            ],
            options={
                'verbose_name': 'ProductImages',
                'verbose_name_plural': 'ProductImages',
            },
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.product')),
            ],
            options={
                'verbose_name': 'ProductCategories',
                'verbose_name_plural': 'ProductCategories',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributesValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=45)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('product_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.productattributes')),
            ],
            options={
                'verbose_name': 'ProductAttributesValues',
                'verbose_name_plural': 'ProductAttributesValues',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributesAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.productattributes')),
                ('product_attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.productattributesassoc')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.product')),
            ],
            options={
                'verbose_name': 'ProductAttributesAssoc',
                'verbose_name_plural': 'ProductAttributesAssoc',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.product')),
            ],
            options={
                'verbose_name': 'OrderDetails',
                'verbose_name_plural': 'OrderDetails',
            },
        ),
        migrations.CreateModel(
            name='CouponsUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('created_date', models.DateField()),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdminPanel.coupon')),
            ],
            options={
                'verbose_name': 'UsedCoupons',
                'verbose_name_plural': 'UsedCoupons',
            },
        ),
    ]
