# Generated by Django 3.2 on 2022-08-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='to_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('M', 'MANAGER'), ('C', 'USER')], default='', max_length=10),
        ),
    ]
