# Generated by Django 3.2 on 2022-08-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdminPanel', '0002_auto_20220825_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('M', 'manager'), ('C', 'user')], default='', max_length=10),
        ),
    ]
