# Generated by Django 3.2 on 2022-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdminPanel', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('M', 'manager'), ('C', 'customer'), ('A', 'admin')], default='', max_length=10),
        ),
    ]
