# Generated by Django 3.2 on 2022-08-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdminPanel', '0005_user_group'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banners',
            table='customAdminPanel_banners',
        ),
    ]
