# Generated by Django 3.2 on 2022-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdminPanel', '0006_alter_banners_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='banner_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
