# Generated by Django 3.2 on 2022-09-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdminPanel', '0007_banners_banner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='banner_name',
            field=models.CharField(max_length=50),
        ),
    ]
